// <auto-generated />
using System;
using Inventory.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Api.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Models.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ImportedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("imported_by");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("int")
                        .HasColumnName("invalid_rows");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRows")
                        .HasColumnType("int")
                        .HasColumnName("valid_rows");

                    b.HasKey("Id");

                    b.HasIndex("ImportedById");

                    b.ToTable("import_batches", null, t =>
                        {
                            t.HasCheckConstraint("CK_import_batches_invalid_rows", "[invalid_rows] >= 0");

                            t.HasCheckConstraint("CK_import_batches_total_rows", "[total_rows] >= 0");

                            t.HasCheckConstraint("CK_import_batches_valid_rows", "[valid_rows] >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Api.Models.ImportBatchError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int")
                        .HasColumnName("row_number");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("IX_import_batch_errors_import_batch_id");

                    b.ToTable("import_batch_errors", null, t =>
                        {
                            t.HasCheckConstraint("CK_import_batch_errors_row_number", "[row_number] > 0");
                        });
                });

            modelBuilder.Entity("Inventory.Api.Models.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PreviousStock")
                        .HasColumnType("int")
                        .HasColumnName("previous_stock");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<int>("ResultingStock")
                        .HasColumnType("int")
                        .HasColumnName("resulting_stock");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_inventory_movements_branch_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_inventory_movements_created_at");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_inventory_movements_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_inventory_movements_user_id");

                    b.ToTable("inventory_movements", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_movements_previous_stock", "[previous_stock] >= 0");

                            t.HasCheckConstraint("CK_inventory_movements_quantity", "[quantity] > 0");

                            t.HasCheckConstraint("CK_inventory_movements_resulting_stock", "[resulting_stock] >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Api.Models.NotificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_notification_tokens_token");

                    b.HasIndex("UserId");

                    b.ToTable("notification_tokens", (string)null);
                });

            modelBuilder.Entity("Inventory.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MinStock")
                        .HasColumnType("int")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sku");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("UX_products_barcode_filtered")
                        .HasFilter("[barcode] IS NOT NULL");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_products_sku");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_min_stock", "[min_stock] >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Api.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int")
                        .HasColumnName("available_quantity");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("LastMovementAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_movement_at");

                    b.Property<Guid?>("LastMovementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_movement_id");

                    b.Property<int>("MinStock")
                        .HasColumnType("int")
                        .HasColumnName("min_stock");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("LastMovementId");

                    b.HasIndex("ProductId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UX_stocks_product_id_branch_id");

                    b.ToTable("stocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_stocks_available_quantity", "[available_quantity] >= 0");

                            t.HasCheckConstraint("CK_stocks_min_stock", "[min_stock] >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Api.Models.ImportBatch", b =>
                {
                    b.HasOne("Inventory.Api.Models.AppUser", "ImportedBy")
                        .WithMany("ImportBatches")
                        .HasForeignKey("ImportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportedBy");
                });

            modelBuilder.Entity("Inventory.Api.Models.ImportBatchError", b =>
                {
                    b.HasOne("Inventory.Api.Models.ImportBatch", "ImportBatch")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Inventory.Api.Models.InventoryMovement", b =>
                {
                    b.HasOne("Inventory.Api.Models.Branch", "Branch")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Api.Models.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Api.Models.AppUser", "User")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory.Api.Models.NotificationToken", b =>
                {
                    b.HasOne("Inventory.Api.Models.AppUser", "User")
                        .WithMany("NotificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory.Api.Models.Stock", b =>
                {
                    b.HasOne("Inventory.Api.Models.Branch", "Branch")
                        .WithMany("Stocks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Api.Models.InventoryMovement", "LastMovement")
                        .WithMany()
                        .HasForeignKey("LastMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Inventory.Api.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("LastMovement");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventory.Api.Models.AppUser", b =>
                {
                    b.Navigation("ImportBatches");

                    b.Navigation("InventoryMovements");

                    b.Navigation("NotificationTokens");
                });

            modelBuilder.Entity("Inventory.Api.Models.Branch", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Inventory.Api.Models.ImportBatch", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("Inventory.Api.Models.Product", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
